### ISSUE TITLE
ReferenceOutputAssembly=false -> Attributes

### ISSUE THREAD

**Issue by Pjotrtje** [excubo-ag/Generators.Blazor#1]
Hello! 
I love the RequiredAttribute and the analysis it provides! But I think this package can be improved when the Attributes are also generated. Because they are now 'real' we need a reference to Excubo.Generators.Blazor which we otherwise do not need. When the attribute is generated we could change this:

`<PackageReference Include="Excubo.Generators.Blazor" Version="1.11.3" />`

to

`<PackageReference Include="Excubo.Generators.Blazor" Version="1.11.3" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>`

which reduces the extra dll when downloading Blazor for WASM.

I can image it would work like this (and maybe for all the other Attributes/public 'interface' classes):

```
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Excubo.Generators.Blazor
{
    [Generator]
    public partial class AddAttributeAnalyzer : ISourceGenerator
    {
        private const string AttributeText = @"
using System;

namespace Excubo.Generators.Blazor
{
    [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = true)]
    public sealed class RequiredAttribute : Attribute
    {
    }
}";

        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("RequiredAttribute.generated.cs", SourceText.From(AttributeText, Encoding.UTF8));
        }
    }
}
```

Or maybe combine them in the current analyser.

**Comment by stefanloerwald** [comment]
Hi @Pjotrtje,

you are correct that this change is indeed possible. There are some caveats though:

1. The IDE sometimes behaves oddly when the types are only added via the source generator. This is hopefully only a temporary thing, but very much still a reality. It isn't a nice user experience lacking auto-complete on these types, because it destroys discoverability and makes people think that there are errors. I find that awful.
2. Nesting. Suppose you write library A that uses `Excubo.Generators.Blazor`. Awesome. Suppose it doesn't reference the output assembly. Now your user wants to also use `Excubo.Generators.Blazor`. Conflict. The two analyzer package references are independent and will both produce the same types. Ouch.

That said, I really wouldn't want to change this. But there is a problem here that we should address: How big is the impact for the blazor wasm scenario? How much does actually get downloaded? Maybe there are other things we can improve to get the download size to an absolutely tiny amount.

BR
Stefan

**Comment by stefanloerwald** [comment]
My quick test I did shows 53.4kB transferred over the network. That's certainly not 0, and more than I want, but not an absurdly high amount either. That's for `dll`, no compression.

**Comment by Pjotrtje** [comment]
That was quick!

Ah the first is a real issue. I can image that is a deal breaker. Check. Maybe later when a release of VS fixes this. But I think I agree with you here.
About the second . If you generatie it as an internal Attribute I think this is not an issue?

About the impact. Well, I am trying out Blazor for first time. And to my anoyance the startup/download speed is **horrible** and whatever we can lose/improve is nice.

**Comment by stefanloerwald** [comment]
True, with internal attributes, this is avoidable, I think. But well, point 1 still stands, sadly.

The impact seems to be around 0.2% for a basic blazor app (The one I'm looking at has 18.1 MB for dlls in total and the 53.4kB for Excubo.Blazor.Generators).

I think the concentrated effort should be to have
- tree shaking enabled (sadly there are still bugs in the linker, so not always workign)
- disabled unused features, see https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-performance-best-practices.md#disable-unused-features

These things will impact your initial download size the most. I hope that helps.

**Comment by Pjotrtje** [comment]
I have allready disabled those :). But thanks.
Ok, then for now close this one I guess.
Thanks for the quick response!
And maybe when VS improves in the near future I will 'reopen' this one =).

**Comment by stefanloerwald** [comment]
Great, let's do it like that.

Just a last thought: the generator probably works fine with the types being defined elsewhere too. So you can add ` OutputItemType="Analyzer" ReferenceOutputAssembly="false"` to your package reference, and just copy the types into your assembly. As long as the namespace and type name matches, that shouldn't be problematic. The attributes will still end up in the compiled assembly, but nothing else of the analyzer assembly will.

Best of luck for your goal to reduce startup time / download size!
